selinux role:  Changed Reboot process
ericsysmin/ansible-collection-system pull request #10
Opened 2021-03-04 12:39 UTC by Fishy78

- Replaced the reboot process with the ansible reboot process
- Changed the selinux.changed condition to selinux.reboot_required

2022-03-10 18:44 UTC, ericsysmin commented
@Fishy78 can you make the suggested changes?

2022-03-10 18:44 UTC, ericsysmin requested changes

2022-03-10 18:44 UTC, ericsysmin commented on roles/selinux/tasks/main.yml
> +  reboot:
```suggestion
  ansible.builtin.reboot:
```

2022-03-10 18:44 UTC, ericsysmin commented on roles/selinux/tasks/main.yml
> +  reboot:
We also need to note that with the change it's only supported in 2.7 or later. Which is fine. I will include this in the new release I'm working on.

2022-03-10 20:07 UTC, ericsysmin approved these changes

2022-03-10 20:07 UTC, merged

2022-03-11 08:27 UTC, Fishy78 commented
Sorry, you were too quick ;)